### ISSUE TITLE
Date range input: Clicking on the second date field opens the first one

### ISSUE THREAD

**Issue by brunobuddy** [case-app/case#38]

**Comment by ismaelguerrib** [comment]
I don't know if it's something we want but there's an other way to do a date range in only one input. https://github.com/kekeh/angular-mydatepicker/wiki/limit-date-range

This solution seems to be the perfect one because as we can't give an other dp.name to the calendars than "angular-mydatepicker".


Otherwise, we can use angular material which can be a more efficient and strong way because more stable than the date-picker package 

https://material.angular.io/components/datepicker/overview
